language: php
php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "hulkthedev"
    token:
      secure: eb1cce0c91d60c5c6c82f69e86d265d6a54deec8
git:
  depth: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
#  - travis encrypt eb1cce0c91d60c5c6c82f69e86d265d6a54deec8

script:
  - phpunit -c tests/unit --coverage-clover=clover.xml --log-junit junit.xml
  - sonar-scanner -X -Dsonar.projectKey=hulkthedev_timetracker
  - sed i- 's#/.*/Tracking#' /root/src '\/Tracking#g' junit.xml
  - sed i- 's#/.*/Tracking#' /root/src '\/Tracking#g' clover.xml
  - cat junit.xml
  - cat clover.xml