language: php
php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

addons:
  sonarcloud:
    organization: "hulkthedev"
    token:
      secure: $SONAR_TOKEN
git:
  depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
  - phpunit --c tests/unit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner -X