language: php
php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "hulkthedev"
    token:
      secure: SONAR_TOKEN
git:
  depth: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit -c tests/unit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner -X -Dsonar.projectKey=SONAR_PROJECT_KEY -Dsonar.login=SONAR_TOKEN