version: '3'composer update --no-interaction --no-suggest --no-progress
services:
  timetracker:
    image: timertracker:latest
    build:
        context: .
    volumes:
      - .:/var/www/html
    ports:
        - 81:80
